### ISSUE TITLE
Breakpoint marker not shown in vertical editor ruler

### ISSUE THREAD

**Issue by castortech** [eclipse-jdt/eclipse.jdt.debug#170]
Noticing that I have lost the vertical editor ruler breakpoint marker, which seems to have happened after upgrading to 4.26 (22-12).

**Comment by SarikaSinha** [comment]
Can you attach a sample porject and screenshot, I could not reproduce with  I20230103-1800

**Comment by castortech** [comment]
Here you go
![image](https://user-images.githubusercontent.com/85858/210548261-12df919e-2d3e-49bc-a758-a6b262694415.png)
[BreakpointMarker.zip](https://github.com/eclipse-jdt/eclipse.jdt.debug/files/10343734/BreakpointMarker.zip)

**Comment by iloveeclipse** [comment]
Can you please switch the theme to default one and/or try with a **new** workspace? I assume either you don't see the right ruler annotation because of the dark theme or because the breakpoint annotation is **disabled** in your workspace preferences.
Here is what I have (and it works fine in alll SDK versions I use and we've shipped in the past):
![image](https://user-images.githubusercontent.com/964108/210548995-743d6207-a699-4470-837a-248adc53abad.png)

**Comment by castortech** [comment]
What I just sent was with a new workspace but my Overview ruler was unchecked. And clearly not sure why it changed but I also seem to have C/C++ installed (2 breakpoint listed) and don't recall ever installing that.

Anyway all is good and thanks and sorry for the false reporting, after using Eclipse for almost 20 years.
