### ISSUE TITLE
Replace use of OPTION_JdtDebugCompileMode with OPTION_IgnoreUnnamedModuleForSplitPackage

### ISSUE THREAD

**Issue by trancexpress** [eclipse-jdt/eclipse.jdt.debug#260]
See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/445, with https://github.com/eclipse-jdt/eclipse.jdt.core/pull/424 we have a better option to fix https://bugs.eclipse.org/bugs/show_bug.cgi?id=543604. So we should use this option and revert changes in JDT core that cause unexpected side effects.

**Comment by stephan-herrmann** [comment]
[I learned](https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/309) that `OPTION_IgnoreUnnamedModuleForSplitPackage` is not sufficient for JDT/Debug, because we may be facing a conflict between **two named modules**, which is not covered by the newer option.

I'm improving interpretation of `OPTION_JdtDebugCompileMode` via https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2340 and when that is merged I suggest to revert the change in this issue.

**Comment by stephan-herrmann** [comment]
> I'm improving interpretation of OPTION_JdtDebugCompileMode via https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2340 and when that is merged I suggest to revert the change in this issue.

https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2340 has been merged. Ready for revert :)

**Comment by iloveeclipse** [comment]
> > I'm improving interpretation of OPTION_JdtDebugCompileMode via [eclipse-jdt/eclipse.jdt.core#2340](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2340) and when that is merged I suggest to revert the change in this issue.
> 
> [eclipse-jdt/eclipse.jdt.core#2340](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2340) has been merged. Ready for revert :)

With "revert" you mean reverting https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/261 I assume?

I will close this ticket again, as we can't "revert ticket" and "fixing it again" would be the opposite of what the ticket says.

The right ticket to fix is https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/309
