### ISSUE TITLE
[test] ConditionalBreakpointsWithFileClass fails on linux since I20241106-1800

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.debug#557]
on all JDKs:
```
Didn't suspend at the expected line expected:<20> but was:<364>

junit.framework.AssertionFailedError: Didn't suspend at the expected line expected:<20> but was:<364>
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.failNotEquals(Assert.java:329)
at junit.framework.Assert.assertEquals(Assert.java:78)
at junit.framework.Assert.assertEquals(Assert.java:234)
at junit.framework.TestCase.assertEquals(TestCase.java:377)
at org.eclipse.jdt.debug.tests.breakpoints.ConditionalBreakpointsWithFileClass.testFileConditionalBreakpointforFalse(ConditionalBreakpointsWithFileClass.java:44)
```
https://download.eclipse.org/eclipse/downloads/drops4/I20241106-1800/testResults.php

**Comment by jukzi** [comment]
@SougandhS do you have Linux, so that you can reproduce locally? i does not fail on windows.

**Comment by SougandhS** [comment]
> @SougandhS do you have Linux, so that you can reproduce locally? it does not fail on windows.

Will configure one and check this. 👍

**Comment by SougandhS** [comment]
Hi @jukzi , I have tested the same on linux local, it is failing. 
I just went through the console logs of tests, turns out every conditional evaluation is throwing error compilation error in linux
https://download.eclipse.org/eclipse/downloads/drops4/I20241106-1800/testresults/ep434I-unit-linux-x86_64-java17_linux.gtk.x86_64_17/org.eclipse.jdt.debug.tests.AutomatedSuite.txt
<img width="869" alt="image" src="https://github.com/user-attachments/assets/718dc3fd-e71d-4b60-8789-57243053b509">

**Comment by SougandhS** [comment]
Latest Ibuild it is not showing. and the console logs are also clean..

**Comment by jukzi** [comment]
Can you find out, why it does not compile anymore? For example a recent commit in jdt.core or ui. Then file a bug against that project, link it. May also make sense to Improve the test to fail with the rootcause.

**Comment by SougandhS** [comment]
> Can you find out, why it does not compile anymore? For example a recent commit in jdt.core or ui. Then file a bug against that project, link it. May also make sense to Improve the test to fail with the rootcause.

Did went through the latest commits in JDT core but couldn't find any related ones. but now it is fixed automatically. - bit confused here, still investigating about it..

**Comment by jukzi** [comment]
Maybe SWT?

**Comment by SougandhS** [comment]
> Maybe SWT?

its only because of the generated Compilation unit is different in linux. and that is solely based on the output from ASTengine from jdt core. Im not sure changes in SWT affects this.
Left - Mac 
Right - Linux 
<img width="756" alt="image" src="https://github.com/user-attachments/assets/5dbd7169-17ba-4250-8b21-f7ab48e22fc5">
